"""Export pacer golden-test fixtures from the counter captures as C headers.

Usage: python3 export_fixtures.py OUT_DIR captures/cms-counter-*.pcap.xz
"""
import os
import re
import sys

from usbpcap import read


def export(path, out_dir):
    rate = int(re.search(r"(\d+)\.pcap", path).group(1))
    urbs = list(read(path))
    last_set = max(u.ts for u in urbs if u.transfer == 2 and u.data[:2] == b"\x22\x01")
    start = last_set + 0.05
    fb = [u.data[o] for u in urbs if u.endpoint == 0x81 and u.completion and u.ts > start
          for o, n, _ in u.iso if n >= 1]
    out = [n // 12 for u in urbs if u.endpoint == 0x02 and not u.completion and u.transfer == 0 and u.ts > start
           for _, n, _ in u.iso]

    def arr(name, vals):
        body = ",".join(str(v) for v in vals)
        return f"static const unsigned char {name}[{len(vals)}] = {{{body}}};\n"

    dest = os.path.join(out_dir, f"counter_{rate}.h")
    with open(dest, "w") as f:
        f.write(f"/* Generated by dynacord-cms-pcap/tools/export_fixtures.py from {os.path.basename(path)} */\n")
        f.write(arr(f"fb_{rate}", fb))
        f.write(arr(f"out_{rate}", out))
    print(f"{dest}: {len(fb)} feedback ms, {len(out)} OUT packets")


if __name__ == "__main__":
    for p in sys.argv[2:]:
        export(p, sys.argv[1])
